#################################################################################
 # Copyright (C) 2025 the Eclipse BaSyx Authors
 # Copyright (C) 2025 SAP SE
 #
 # Permission is hereby granted, free of charge, to any person obtaining
 # a copy of this software and associated documentation files (the
 # "Software"), to deal in the Software without restriction, including
 # without limitation the rights to use, copy, modify, merge, publish,
 # distribute, sublicense, and/or sell copies of the Software, and to
 # permit persons to whom the Software is furnished to do so, subject to
 # the following conditions:
 #
 # The above copyright notice and this permission notice shall be
 # included in all copies or substantial portions of the Software.
 #
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 # EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 # MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 # NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 # LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 # OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 # WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 #
 # SPDX-License-Identifier: MIT
#################################################################################

---
imagePullSecrets: []

image: 
  name: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
  pullPolicy: IfNotPresent

resources: {}
podAnnotations: {}

service:
  type: ClusterIP
  port: 8080

startup:
  enabled: false
  # Currently supporting a GitRepo source for startup AAS shells, but must be a public repo.
  repo: ""
  # Other sources may be defined later.

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  host: aas-environment.local
  tls: []

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

apirule:
  enabled: false
  host: aas-environment.local
  methods: 
      - "GET" 
      - "HEAD" 
      - "POST" 
      - "PUT" 
      - "DELETE" 
      - "CONNECT" 
      - "OPTIONS" 
      - "TRACE"
      - "PATCH"
  # -- Allows configuring CORS headers sent with the response. If corsPolicy is not defined, the CORS headers are enforced to be empty.
  corsPolicy: 
    allowMethods:
    - POST
    - GET
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
    - HEAD
    allowOrigins:
      - regex: ".*" # allow all origins
    allowCredentials: true

config: |
  basyx.backend = MongoDB
  spring.data.mongodb.host=mongo
  spring.data.mongodb.database=aas-env
  spring.data.mongodb.authentication-database=admin
  spring.data.mongodb.username=mongoAdmin
  spring.data.mongodb.password=mongoPassword

  basyx.environment=file:aas
  basyx.aasrepository.feature.mqtt.enabled = true
  basyx.cors.allowed-origins=*

  mqtt.clientId=AAS-Env-Example-8081
  mqtt.hostname = mqtt
  mqtt.port = 1884

  basyx.feature.authorization.enabled = true
  basyx.feature.authorization.type = rbac
  basyx.feature.authorization.jwtBearerTokenProvider = keycloak
  basyx.feature.authorization.rbac.file = file:/application/rbac_rules.json
  spring.security.oauth2.resourceserver.jwt.issuer-uri= http://keycloak.basyx.local:8080/realms/BaSyx

rbac:
  rules: |
    [
      {
        "role": "basyx-reader",
        "action": "READ",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "*",
          "submodelElementIdShortPaths": "*"
        }
      },
      {
        "role": "admin",
        "action": ["CREATE", "READ", "UPDATE", "DELETE", "EXECUTE"],
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "*",
          "submodelElementIdShortPaths": "*"
        }
      },
      {
        "role": "basyx-reader-two",
        "action": "READ",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "specificSubmodelId",
          "submodelElementIdShortPaths": "*"
        }
      },
      {
        "role": "basyx-sme-reader",
        "action": "READ",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": ["specificSubmodelId", "testSMId1", "testSMId2"],
          "submodelElementIdShortPaths": ["testSMEIdShortPath1","smc2.specificSubmodelElementIdShort","testSMEIdShortPath2"]
        }
      },
      {
        "role": "basyx-sme-reader-two",
        "action": "READ",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "specificSubmodelId",
          "submodelElementIdShortPaths": "smc2.specificFileSubmodelElementIdShort"
        }
      },
      {
        "role": "basyx-creator",
        "action": "CREATE",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "*",
          "submodelElementIdShortPaths": "*"
        }
      },
      {
        "role": "basyx-updater",
        "action": "UPDATE",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "*",
          "submodelElementIdShortPaths": "*"
        }
      },
      {
        "role": "basyx-updater-two",
        "action": "UPDATE",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "specificSubmodelId",
          "submodelElementIdShortPaths": "*"
        }
      },
      {
        "role": "basyx-sme-updater",
        "action": "UPDATE",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "specificSubmodelId",
          "submodelElementIdShortPaths": "smc2.specificFileSubmodelElementIdShort"
        }
      },
      {
        "role": "basyx-sme-updater-two",
        "action": "UPDATE",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "specificSubmodelId",
          "submodelElementIdShortPaths": "smc2"
        }
      },
      {
        "role": "basyx-sme-updater-three",
        "action": "UPDATE",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "specificSubmodelId-2",
          "submodelElementIdShortPaths": "smc1.specificSubmodelElementIdShort-2"
        }
      },
      {
        "role": "basyx-file-sme-updater",
        "action": "UPDATE",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "specificSubmodelId-2",
          "submodelElementIdShortPaths": "smc2.specificFileSubmodelElementIdShort"
        }
      },
      {
        "role": "basyx-deleter",
        "action": "DELETE",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "*",
          "submodelElementIdShortPaths": "*"
        }
      },
      {
        "role": "basyx-deleter-two",
        "action": "DELETE",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "specificSubmodelId-2",
          "submodelElementIdShortPaths": "*"
        }
      },
      {
        "role": "basyx-executor",
        "action": "EXECUTE",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "*",
          "submodelElementIdShortPaths": "*"
        }
      },
      {
        "role": "basyx-executor-two",
        "action": "EXECUTE",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "specificSubmodelId",
          "submodelElementIdShortPaths": "square"
        }
      },
      {
        "role": "basyx-file-sme-reader",
        "action": "READ",
        "targetInformation": {
          "@type": "submodel",
          "submodelIds": "specificSubmodelId-2",
          "submodelElementIdShortPaths": "smc2.specificFileSubmodelElementIdShort"
        }
      }
    ]
